suppressPackageStartupMessages({

    ########### main libraries ###########
    library(qiime2R) # QIIME 2 import
    library(dada2) # taxonomy assignment
    
    # mia data structures
    library(TreeSummarizedExperiment)
    library(mia)
    library(miaViz) # mia visualizatioon
    

    ########### data manipulation tools ###########
    library(tidyverse)
    
    ########### visualization libraries ###########
    
    # library(ggpubr)
    # library(pheatmap)
    # library(readr)
    # library(RColorBrewer)
    # library(colorspace)
    # library(cowplot)
    # library(grid)
    # library(patchwork)
    # library(gridExtra)
    # library(ggrepel)
    # library(ggpubr)
    # library(ggthemes)
    # library(RColorBrewer)
    # library(patchwork)
    # library(cowplot)
    
    ########### resource management tools ###########
    library(tictoc)

    ### loaded by tidyverse
    # library(ggplot2)
    # library(tidyr)
    # library(dplyr)
    # library(readr)
    # library(stringr)
})



warnLevel <- getOption('warn')
options(warn = -1)



args <- commandArgs(trailingOnly = TRUE)
if (length(args) >= 2) {
    PROJECT_NAME <- args[1]
    PROJECT_DIR  <- normalizePath(args[2])
} else {
    # defaults for notebook 
    PROJECT_NAME <- "ERP000133"
    PROJECT_DIR  <- normalizePath("..")
}

INITIAL_QC_DIR <- file.path(PROJECT_DIR, "initial_qc")
DADA2_INPUT_DIR <- file.path(INITIAL_QC_DIR, "qiime2", "dada2")
PHYLO_INPUT_DIR <- file.path(INITIAL_QC_DIR, "qiime2", "phylo")

SILVA_TRAINSET_GENUS_FILE <- file.path(PROJECT_DIR, "taxonomy_training_classifiers", "silva_nr99_v138.2_toGenus_trainset.fa.gz")
SILVA_TRAINSET_SPECIES_FILE <- file.path(PROJECT_DIR, "taxonomy_training_classifiers", "silva_nr99_v138.2_toSpecies_trainset.fa.gz")


dada2_file_path <- function(suffix) {
    filename = file.path(DADA2_INPUT_DIR, paste0(PROJECT_NAME, ".qiime.dada2.", suffix))
    return (filename)
}

rep_seqs <- read_qza(dada2_file_path("rep_seqs.qza")) # representative sequences, generated by QIIME 2's implementation of DADA2
asv_table <- read_qza(dada2_file_path("asv_table.qza")) # ASV table, generated by QIIME 2's implementation of DADA2
denoising_stats <- read_qza(dada2_file_path("denoising_stats.qza")) # denoising statistics, generated by QIIME 2's implementation of DADA2
base_transition_stats <- read_qza(dada2_file_path("base_transition_stats.qza"))

rooted_tree <- read_qza(file.path(PHYLO_INPUT_DIR, paste0(PROJECT_NAME, ".qiime.phylo.", "rooted_tree.qza"))) # rooted tree of sequences, generated by QIIME 2's phylogeny function

sample_metadata_tse <- read_tsv(
    file.path(PROJECT_DIR, "summary_tables", paste0(PROJECT_NAME, ".qc_summary_table_for_TSE.tsv")), # sample metadata table made for making the TSE object, generated by the create_qc_summary_tables script/notebook
    show_col_types = FALSE
) |>
    tibble::column_to_rownames("sample_id")



# make file output directory if it doesn't already exist
TAXA_DIR <- file.path(PROJECT_DIR, "taxonomy_assignment")
dir.create(TAXA_DIR, recursive = TRUE, showWarnings = FALSE)


# print(class(rep_seqs$data)) # check class of representative sequences data element
# str(rep_seqs$data) # check object structure

# extract sequences, name by rep_seq data names
seqs <- as.character(rep_seqs$data)
names(seqs) <- names(rep_seqs$data)
# head(seqs)

# print(length(seqs)) # check how many representatice sequences there are in the dataset
# head(seqs)

set.seed(100) # initialize random number generator for reproducibility

# Assign taxonomies at the genus level
tic()
taxa_genus <- assignTaxonomy(
    seqs,
    SILVA_TRAINSET_GENUS_FILE,
    multithread = TRUE
)
toc()

# Assign taxonomies at the species level
tic()
taxa_species <- assignTaxonomy(
    seqs,
    SILVA_TRAINSET_SPECIES_FILE,
    multithread = TRUE
)
toc()

taxonomy_summary <- tibble::tibble(
    metric = c(
        "ASVs with no genus assignment",
        "ASVs with no species assignment",
        "Unique assigned genera",
        "Total ASVs"
    ),
    value = c(
        sum(is.na(taxa_genus[, "Genus"])),
        sum(is.na(taxa_species[, "Species"])),
        length(unique(na.omit(taxa_genus[, "Genus"]))),
        nrow(taxa_genus)
    )
)

# add percentages
taxonomy_summary <- taxonomy_summary |>
    dplyr::mutate(
        percent = c(
            100 * value[1] / nrow(taxa_genus),
            100 * value[2] / nrow(taxa_species),
            NA,
            NA
        )
    )

# print a clean taxonomy QC summary
cat("TAXONOMY ASSIGNMENT SUMMARY\n")
cat("===========================\n\n")
print(taxonomy_summary, n = Inf)

# check the top most common genera by number of ASVs assigned to each genus
top_genera <- sort(
    table(taxa_genus[, "Genus"]),
    decreasing = TRUE
) |>
    head(10) |>
    as.data.frame() |>
    dplyr::rename(
        Genus = Var1,
        ASV_count = Freq
    )

cat("\n\nTOP 10 GENERA BY NUMBER OF ASVs\n")
cat("===============================\n\n")
print(top_genera, row.names = FALSE)

cat("\n\nTAXONOMY OBJECT INFO\n")
cat("====================\n\n")

cat("class:      ", paste(class(taxa_genus), collapse = ", "), "\n")
cat("dimensions: ", nrow(taxa_genus), "ASVs x", ncol(taxa_genus), "taxonomic ranks\n")
cat("ranks:      ", paste(colnames(taxa_genus), collapse = ", "), "\n")

cat("\n\nFIRST 6 TAXONOMY ASSIGNMENTS\n")
cat("============================\n\n")

taxa_genus |>
    head(6) |>
    as.data.frame() |>
    tibble::rownames_to_column("ASV_sequence") |>
    print()

# check how many ASVs could be classified at each taxonomic rank
taxonomic_assignment_summary <- tibble::tibble(
    Taxonomic_rank = colnames(taxa_genus),
    Assigned_ASVs = colSums(!is.na(taxa_genus))
) |>
    dplyr::mutate(
        Total_ASVs = nrow(taxa_genus),
        Percent_assigned = round(
            100 * Assigned_ASVs / Total_ASVs,
            digits = 1
        )
    )

cat("TAXONOMIC ASSIGNMENT BY RANK\n")
cat("============================\n\n")

print(
    taxonomic_assignment_summary,
    n = Inf
)

# make a few basic taxonomy QC summaries
taxonomy_summary_species <- tibble::tibble(
    metric = c(
        "ASVs with no genus assignment",
        "ASVs with no species assignment",
        "Unique assigned genera",
        "Unique assigned species",
        "Total ASVs"
    ),
    value = c(
        sum(is.na(taxa_species[, "Genus"])),
        sum(is.na(taxa_species[, "Species"])),
        length(unique(na.omit(taxa_species[, "Genus"]))),
        length(unique(na.omit(taxa_species[, "Species"]))),
        nrow(taxa_species)
    )
)

# add percentages 
taxonomy_summary_species <- taxonomy_summary_species |>
    dplyr::mutate(
        percent = c(
            100 * value[1] / nrow(taxa_species),
            100 * value[2] / nrow(taxa_species),
            NA,
            NA,
            NA
        )
    )


cat("TAXONOMY ASSIGNMENT SUMMARY\n")
cat("===========================\n\n")
print(taxonomy_summary_species, n = Inf)







# check the top most common genera by number of ASVs assigned to each genus
top_genera_species <- sort(
    table(taxa_species[, "Genus"]),
    decreasing = TRUE
) |>
    head(10) |>
    as.data.frame() |>
    dplyr::rename(
        Genus = Var1,
        ASV_count = Freq
    )

cat("\n\nTOP 10 GENERA BY NUMBER OF ASVs\n")
cat("===============================\n\n")
print(top_genera_species, row.names = FALSE)

# check the top most common species by number of ASVs assigned to each species
top_species_species <- sort(
    table(taxa_species[, "Species"]),
    decreasing = TRUE
) |>
    head(10) |>
    as.data.frame() |>
    dplyr::rename(
        Species = Var1,
        ASV_count = Freq
    )

cat("\n\nTOP 10 SPECIES BY NUMBER OF ASVs\n")
cat("================================\n\n")
print(top_species_species, row.names = FALSE)

cat("\n\nTAXONOMY OBJECT INFO\n")
cat("====================\n\n")

# cat("class:      ", paste(class(taxa_species), collapse = ", "), "\n")
cat("dimensions: ", nrow(taxa_species), "ASVs x", ncol(taxa_species), "taxonomic ranks\n")
cat("ranks:      ", paste(colnames(taxa_species), collapse = ", "), "\n")

cat("\n\nFIRST 6 TAXONOMY ASSIGNMENTS\n")
cat("============================\n\n")

taxa_species |>
    head(6) |>
    as.data.frame() |>
    tibble::rownames_to_column("ASV_sequence") |>
    print()

# check how many ASVs could be classified at each taxonomic rank
taxonomic_assignment_summary_species <- tibble::tibble(
    Taxonomic_rank = colnames(taxa_species),
    Assigned_ASVs = colSums(!is.na(taxa_species))
) |>
    dplyr::mutate(
        Total_ASVs = nrow(taxa_species),
        Percent_assigned = round(
            100 * Assigned_ASVs / Total_ASVs,
            digits = 1
        )
    )

cat("TAXONOMIC ASSIGNMENT BY RANK\n")
cat("============================\n\n")

print(
    taxonomic_assignment_summary_species,
    n = Inf
)

# genus
#    rds
saveRDS(
    taxa_genus,
    file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_genus.rds"))
)

#    tsv
write_tsv(
    as.data.frame(taxa_genus) |>
        tibble::rownames_to_column("feature_id"),
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_genus.tsv"))
)




# summary
write_tsv(
   taxonomy_summary,
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_genus.taxonomy_summary.tsv"))
)


# assignment summary
write_tsv(
   taxonomic_assignment_summary,
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_genus.taxonomy_assignment_rate_summary.tsv"))
)


# genus
#    rds
saveRDS(
    taxa_species,
    file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_species.rds"))
)

#    tsv
write_tsv(
    as.data.frame(taxa_species) |>
        tibble::rownames_to_column("feature_id"),
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_species.tsv"))
)




# summary
write_tsv(
   taxonomy_summary_species,
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_species.taxonomy_summary.tsv"))
)


# assignment summary
write_tsv(
   taxonomic_assignment_summary_species,
   file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".taxa_species.taxonomy_assignment_rate_summary.tsv"))
)


head(asv_table$data)

# taxa_genus2 <- taxa_genus 

# switch the taxonomy rownames from sequences back to the QIIME ASV ids
rownames(taxa_genus) <- names(rownames(taxa_genus))

# sum(rownames(asv_table$data) %in% rownames(taxa_genus))

# reorder taxa genus table to match ASV
taxa_genus <- taxa_genus[rownames(asv_table$data), , drop = FALSE]



# reorder sample metadata to match ASV
sample_metadata_tse <- sample_metadata_tse[
    colnames(asv_table$data),
    ,
    drop = FALSE
]
# sample_metadata_tse



# dim(asv_table$data)
# dim(taxa_genus)

# head(rownames(asv_table$data))
# head(rownames(taxa_genus))

# sum(rownames(asv_table$data) %in% rownames(taxa_genus))
# length(rownames(asv_table$data))



tse <- TreeSummarizedExperiment(
    assays = list(counts = as.matrix(asv_table$data)),
    rowData = S4Vectors::DataFrame(taxa_genus),
    colData = S4Vectors::DataFrame(sample_metadata_tse)
)

# colData(tse)

head(colData(tse))

dim(tse)



assayNames(tse)


head(rowData(tse))


head(colData(tse))

colData(tse)$final_read_depth <- colSums(assay(tse, "counts"))
colData(tse)$observed_ASVs <- colSums(assay(tse, "counts") > 0)

colData(tse)$final_read_depth

colData(tse)$observed_ASVs

# Check for missing kingdom assigment
table(rowData(tse)$Kingdom, useNA = "ifany")


# Check for missing Phylum assigment
table(rowData(tse)$Phylum, useNA = "ifany")


as.data.frame(rowData(tse))[is.na(rowData(tse)$Kingdom), ]

rownames(tse)[is.na(rowData(tse)$Kingdom)]

# What's the sequence of the one missing NA Kingdom ASV? 
rep_seqs$data[rownames(tse)[is.na(rowData(tse)$Kingdom)]]



# Check for non-bacterial species 
unique(rowData(tse)$Family[grepl("mitochond", rowData(tse)$Family, ignore.case = TRUE)])
unique(rowData(tse)$Order[grepl("chloroplast", rowData(tse)$Order, ignore.case = TRUE)])

# the ASV(s) with no kingdom assignment
missing_bac <- tse[is.na(rowData(tse)$Kingdom), ]
as.data.frame(rowData(missing_bac))

# NA counts across all samples
as.data.frame(assay(tse, "counts")[is.na(rowData(tse)$Kingdom), ])

#    rds
saveRDS(
    tse,
    file = file.path(TAXA_DIR, paste0(PROJECT_NAME, ".ASV_with_taxa.TSE.rds"))
)



